PREFIX ex: <https://laminhtrung.github.io/movie-lod-semantic-web/ontology#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX res: <https://laminhtrung.github.io/movie-lod-semantic-web/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?s ?label WHERE { ?s a dbo:Actor . FILTER(STRSTARTS(STR(?s), "https://laminhtrung.github.io/movie-lod-semantic-web/resource/")) OPTIONAL { ?s rdfs:label ?label } } ORDER BY ?s
